#!/bin/bash


ping_check() {
	ping -q -w 1 -c 1 192.168.0.1 > /dev/null && echo true || echo false ; 
}


get_weather() {
	check=$(ping_check)
	
	if [ $check == "true" ] ;
	then
		wget 'https://wttr.in/Farmington?u&format=3' -O /tmp/i3_weather ;
		cat /tmp/i3_weather ;
		notify-send -t 2500 -u low "Weather Updated." ;
       		sleep 180 ;
	else
		sleep 10 ;
		return 0 ;
	fi
}

while :
do
	get_weather ;
done
