#!/bin/bash
# script to perform various openvpn activities easier and securely #
# vpn [option] <location> #

# test if root/su for connect, disconnect, location, and status # 
if [[ $1 =~ ^-?-c(onnect)?$|^-?-d(isconnect)?$|^-?-l(ocations)?$|^-?-s(tatus)?$ ]] && [ "$EUID" -ne "0" ] ;
	then echo "Please run as root or super-user!" ;
	exit ;
fi

# location variables #
poland="Windscribe-Poland-GCM.ovpn" ;
canadae="Windscribe-Canada-East-GCM.ovpn" ;
czech="Windscribe-Canada-East-GCM.ovpn" ;
hungary="Windscribe-Hungary-GCM.ovpn" ;
lithuania="Windscribe-Lithuania-GCM.ovpn" ;
russia="Windscribe-Russia-GCM.ovpn" ;
useast="Windscribe-US-East-GCM.ovpn" ;
uscentral="Windscribe-US-Central-GCM.ovpn" ;
windflixus="Windscribe-WINDFLIX-US-GCM.ovpn" ;

# help function #
vpn_help() {
	echo "OpenVPN Utility" ;
	echo "Usage: vpn [option] <location>" ;
	echo "" ;
	echo "	-h,  --help		Print this help message" ;
	echo "	-c,  --connect		Connect to given location" ;
	echo "	-d,  --disconnect	Disconnect from OpenVPN and vpn script" ;
	echo "	-l,  --location		Print list of availible locations" ;
	echo "	-s,  --status		Print status of OpenVPN logfile and current connection" ;
	echo "" ;
}

# location case #
case $2 in
	"poland"|"pol") location=$poland ;;
	"canadaeast"|"cae") location=$canadae ;;
	"czech"|"cz") location=$czech ;;
	"hungary"|"hun") location=$hungary ;;
	"lithuania"|"lit") location=$lithuania ;;
	"russia"|"ru") location=$russia ;;
	"useast"|"use") location=$useast ;;
	"uscentral"|"usc") location=$uscentral ;;
	"windflixus"|"wfus") location=$windflixus ;;
esac


# main functions #
vpn_connect() {
	openvpn --daemon --auth-nocache --status /home/ryan/build/openvpn/openvpn.log 10 --config /home/ryan/build/openvpn/$location ;
}

vpn_disconnect() {
	sudo -u ryan DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -t 2500 "VPN Connection Terminated" ;
	pkill openvpn ;
	pkill vpn ;
} 

vpn_location() {
	echo "VPN Locations:" ;
	echo "" ;
	echo "Poland: poland, pol 		| $poland" ;
	echo "Canada East: canadaeast, cae 	| $canadae" ;
	echo "Czech Republic: czech, cz 	| $czech" ;
	echo "Hungary: hungary, hun 		| $hungary" ;
	echo "Lithuania: lithuania, lit 	| $lithuania" ;
	echo "Russia: russia, ru 		| $russia" ;
	echo "US East: useast, use 		| $useast" ;
	echo "US Central: uscentral, usc 	| $uscentral" ;
	echo "Windflix US: windflixus, wfus 	| $windflixus" ;
	echo "" ;
}

vpn_status() {
	status=$(ip link show | grep tun0 | cut -d" " -f2-) ;
	activeloc=$(ps ax | grep -v grep | grep "vpn -c" | awk 'END{print $NF}') ;
	
	case $activeloc in
		"poland"|"pol") loc=$poland ;;
        	"canadaeast"|"cae") loc=$canadae ;;
        	"czech"|"cz") loc=$czech ;;
        	"hungary"|"hun") loc=$hungary ;;
        	"lithuania"|"lit") loc=$lithuania ;;
        	"russia"|"ru") loc=$russia ;;
        	"useast"|"use") loc=$useast ;;
        	"uscentral"|"usc") loc=$uscentral ;;
        	"windflixus"|"wfus") loc=$windflixus ;;
	esac

	echo "VPN Status:" ;
	echo "Connected to: $loc" ;
	echo "" ;
	if [ -n "$status" ] ;
		then echo "$status" ;
		else echo "No VPN tunnel exists now." ;
	fi
	echo "" ;
	cat /home/ryan/build/openvpn/openvpn.log ;
	echo "" ;
}

# check for openvpn process running and complain if it's not #
vpn_test() {
	while [ -n "$(pgrep vpn)" ] ;
	do
		if [ -n "$(pgrep openvpn)" ] ;
			then sleep 10 ; 
			else sudo -u ryan DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u critical "VPN CONNECTION LOST!" ;
		fi
	done
}

# option if case #
case $1 in
	"-c"|"--connect") vpn_connect ; vpn_test & ;;
	"-d"|"--disconnect") vpn_disconnect ;;
	"-l"|"--location") vpn_location ;;
	"-s"|"--status") vpn_status ;;
	*|"-h"|"--help") vpn_help ;;
esac

